baseURL = 'https://zlemenio.github.io/'
languageCode = 'en-us'
title = 'Lemenio'
theme = "sub-mini"
disqusShortname = "vietkhanhdo"

[params]    
    bio = "amateurasu"
    enableComments = "true"

[social]
github = "https://github.com/zlemenio"
facebook = "https://www.facebook.com/lemeniodo"