baseURL = 'https://lemenio.me/'
languageCode = 'en-us'
title = 'Lemenio'
theme = "sub-mini"
disqusShortname = "vietkhanhdo"

[params]    
    bio = "amateurasu"
    enableComments = "true"
    copyright = "© Copyright 2021 ❤️"
    showPowerBy= "false"

[social]
github = "https://github.com/zlemenio"
facebook = "https://www.facebook.com/lemeniodo"

